title:       Jon Trzaska  # your name (or website title) here
logo: "/images/cropped_me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://www.linkedin.com/in/jonathantrzaska/">LinkedIn</a> 
  <br>
  <a href="/pdf/TRZASKA Jonathan Resume 2022.pdf">Resume</a>  
  <br>
  <a href="https://github.com/JonTRZ">GitHub</a>  
  <br>
  
theme: jekyll-theme-time machine
